module.exports = [
  {
    title: "Am I a Candidate for All-on-4?",
    slug: "all-on-4-candidacy",
    category: "implant-education",
    priority: "High",
    stage: "Drafted",
    patientQuestion: "How do I know if All-on-4 is even possible for me?",
  },
  {
    title: "All-on-4 vs Implant-Supported Dentures",
    slug: "all-on-4-vs-implant-supported-dentures",
    category: "implant-education",
    priority: "High",
    stage: "Drafted",
    patientQuestion: "What is the difference between fixed teeth and snap-on dentures?",
  },
  {
    title: "Full-Mouth Implant Cost in Arizona: What Changes the Price",
    slug: "full-mouth-implant-cost-arizona",
    category: "cost-financing",
    priority: "High",
    stage: "Drafted",
    patientQuestion: "Why do quotes vary so much for full-arch treatment?",
  },
  {
    title: "Same-Day Extractions and Implants: When It Is and Is Not Possible",
    slug: "same-day-extractions-and-implants",
    category: "implant-education",
    priority: "High",
    stage: "Drafted",
    patientQuestion: "Can my failing teeth be removed and implants placed in one visit?",
  },
  {
    title: "Dental Implant Recovery Timeline and Maintenance",
    slug: "implant-recovery-and-maintenance",
    category: "implant-education",
    priority: "High",
    stage: "Planned",
    patientQuestion: "What should recovery feel like and how do I protect my implant long-term?",
  },
  {
    title: "Emergency Dentist vs Emergency Room",
    slug: "emergency-dentist-vs-emergency-room",
    category: "urgent-care",
    priority: "High",
    stage: "Drafted",
    patientQuestion: "When should I call a dentist and when should I go straight to the ER?",
  },
  {
    title: "Severe Tooth Pain After Hours: What to Do First",
    slug: "severe-tooth-pain-after-hours",
    category: "urgent-care",
    priority: "High",
    stage: "Planned",
    patientQuestion: "How do I manage pain safely until the office reopens?",
  },
  {
    title: "Dental Infection and Facial Swelling: Red Flags You Should Not Ignore",
    slug: "dental-infections-and-swelling",
    category: "urgent-care",
    priority: "High",
    stage: "Planned",
    patientQuestion: "What swelling symptoms mean I need urgent medical care now?",
  },
  {
    title: "Simple vs Surgical Tooth Extractions",
    slug: "simple-vs-surgical-extractions",
    category: "extractions-oral-surgery",
    priority: "Medium",
    stage: "Planned",
    patientQuestion: "What makes an extraction surgical, and does that change recovery?",
  },
  {
    title: "Dry Socket Prevention and Early Symptoms",
    slug: "dry-socket-prevention-and-symptoms",
    category: "extractions-oral-surgery",
    priority: "Medium",
    stage: "Planned",
    patientQuestion: "How do I lower dry socket risk and what warning signs should I watch for?",
  },
];
